### ISSUE TITLE
passing credentials for provider.tf for clearblade

### ISSUE THREAD

**Issue by sravyasambaturu** [ClearBlade/terraform-provider-clearblade#11]
Hi I am using ClearBlade iot product from GCP marketplace while writing tf code, I am facing an issue with provider block

It was mentioned that tf code needs service credential based configuration for the Clearblade IoT Core provider soo 

```
provider "clearblade" {
 }
```

<img width="842" alt="image" src="https://github.com/ClearBlade/terraform-provider-clearblade/assets/71900458/be5958d0-ab88-45be-a4a9-f6e3241c232d">

I tried to export CLEARBLADE_CONFIGURATION=/path/to/sa.json

But still it throws the same error as mentioned in the image..
Also I tried to pass the "credentials" argument as well.. still it throws the same error as in image.. 

Help would be appreciated.

**Comment by sravyasambaturu** [comment]
I was able to resolve this.. thanks

**Comment by galah92** [comment]
I'm getting the same error. @sravyasambaturu how did you solve this?
